Add controllers initial commit
Sweta304/java-shareit pull request #1
Opened 2022-08-28 17:25 UTC by Sweta304

2022-08-29 18:30 UTC, alexache requested changes

2022-08-29 18:30 UTC, alexache commented on pom.xml
> +<!--					<plugin>-->
Закомментированный код лучше удалять

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    public ItemDto addItem(ItemDto itemDto, Long owner) throws ValidationException;
public модификатор у методов интерфейса лишний, все методы интерфейса и так считаются публичными

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public static boolean validate(User user) {
Для Item это (валидация) находится в ItemDto, а для User наоборот. Как-то выглядит странно, логично иметь это на *Dto и проверять спрингом, как это было в прошлом проекте

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    public User addUser(User user) throws UserAlreadyExistsException, ValidationException, EmailException;
Тот же комментарий про public методы и интерфейс

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public User addUser(User user) throws UserAlreadyExistsException, ValidationException, UserNotFoundException, EmailException;
Тот же комментарий про public методы и интерфейс

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemDto addItem(ItemDto itemDto, Long owner) throws UserNotFoundException, ValidationException;
Тот же комментарий про public методы и интерфейс

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    public ItemDto addItem(ItemDto itemDto, Long owner) throws ValidationException {
Идея в том, чтобы репозиторий работал только с Item / User, сервис берет на себя конвертацию User <-> UserDto, Item <-> ItemDto, и лучше конвертацию из ItemDto -> Item тоже добавить в ItemMapper, как и для User, а вызывать в сервисах

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        List<ItemDto> foundItemsDto = itemsList.stream().filter(x -> x.getOwner().equals(owner)).map(x -> ItemMapper.toItemDto(x)).collect(Collectors.toList());
Почему эту фильтрацию не сделать в первом же стриме? И возвращаясь к предыдущему комментарию про роли сервиса и репозитория, лучше не конвертировать в репозитории

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        List<Item> foundItems = items.values().stream().filter(x -> (x.getName().toLowerCase().contains(text.toLowerCase()) || x.getDescription().toLowerCase().contains(text.toLowerCase())) && x.getA
Все операции со стримами лучше выносить на новые строки для лучшей читаемости, то есть 
`items.values().stream()`
`   .filter()`
`   .collect()`

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        List<Item> foundItems = items.values().stream().filter(x -> (x.getName().toLowerCase().contains(text.toLowerCase()) || x.getDescription().toLowerCase().contains(text.toLowerCase())) && x.getA
text.toLowerCase() лучше вынести в переменную, чтобы не проделывать эту операцию столько раз

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        if (!User.validate(user)) {
Эту операцию лучше делать не в репозитории, а аннотациями на классе или в сервисе, как и остальные условия ниже.
Почему? Потому что может быть несколько разных реализаций репозитория, и везде придется писать похожий код, как здесь, лучше иметь его в сервисе

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        } else if (user.getId() != null && users.get(user.getId()) != null || (user.getEmail() != null && users.values().stream().filter(x -> x.getEmail().equals(user.getEmail())).collect(Collectors.
Очень длинное и сложное условие, для стримов не хватает переносов, и можно чуть проще сделать с 
`users.values().stream()`
`    .filter(x -> x.getEmail().equals(user.getEmail()))`
`    .findAny()`
`    .isPresent()`

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +            } else if (user.getEmail() != null && users.values().stream().filter(x -> x.getEmail().equals(user.getEmail())).collect(Collectors.toList()).size() > 0) {
Уже второе длинное условие, возможно стоит вынести в метод

2022-08-29 18:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +            users.remove(id);
Это лишняя процедура

2022-09-04 20:22 UTC, Sweta304 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        if (!User.validate(user)) {
Привет! пробовала ставить аннотации на классе -  с ними не проходят тесты в постман

2022-09-05 14:54 UTC, alexache approved these changes
Больше нет комментариев

2022-09-06 18:38 UTC, merged