FEATURE:
Sweta304/java-shareit pull request #2
Opened 2022-09-25 15:25 UTC by Sweta304

- добавлена функция бронирования
- добавлена возможность оставлять комментарии к вещам после бронирования

2022-09-29 17:15 UTC, Sweta304 commented
Снова проблема с тестами - заменяла все настройки на H2, тесты не проходят ни локально, ни тут. На postgresql локально все ок. Никто пока не может помочь( уже сильно опаздываю, отправляю пока так, к сожалению

2022-09-30 21:19 UTC, alexache requested changes

2022-09-30 21:19 UTC, alexache commented on pom.xml
> +			<version>2.7.3</version>
Убрать версию

2022-09-30 21:19 UTC, alexache commented on pom.xml
> +			<version>5.4.17.Final</version>
Убрать версию

2022-09-30 21:19 UTC, alexache commented on pom.xml
> +			<version>42.4.1</version>
Убрать версию

2022-09-30 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +public class PersistenceConfig {
Удалить этот класс. Откуда он взялся?

2022-09-30 21:19 UTC, alexache commented on src/main/resources/application.properties
>  spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect

2022-09-30 21:19 UTC, alexache commented on src/main/resources/application.properties
>  spring.jpa.hibernate.show_sql=true
spring.jpa.properties.hibernate.show_sql

2022-10-02 20:24 UTC, alexache requested changes

2022-10-02 20:24 UTC, alexache commented on pom.xml
> +<!--			<version>42.4.1</version>-->
Закомментированные части лучше сразу удалять

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookStatus.java
> +    ALL,
Мне кажется, тут смешались 2 разных по смыслу енама - один именно про статус/состояние бронирования, а втором для вывода разных вариаций бронирований

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    private Booking booking;
Для чего это поле?

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +/**
Комментарии либо следует наполнить, либо удалить

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingDto addBooking(@RequestBody @Valid Booking booking, @RequestHeader("X-Sharer-User-Id") Long booker) throws ItemNotAvailableException, ItemNotFoundException, IncorrectBookingExceptio
Booking - это класс для хранения данных репозиторием в БД. не для получения их от клиента. Здесь возможно не помешает новый класс-DTO для таких операций добавлений

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "item_id")
Здесь можно воспользоваться аннотациями @ManyToOne, @JoinColumn и получать сразу объекты item и user

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    UserJpaRepository userJpaRepository;
Не хватает модификаторов доступа

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +    private Comment comment;
Непонятно зачем тут это поле

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
>      private Item item;
И это поле непонятно для чего

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemWithBookingDatesDto.java
> +public class ItemWithBookingDatesDto {
Чем это отличается от ItemWithBooking?

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
>  public class ItemRepositoryImpl implements ItemRepository {
Можно уже перестать поддерживать этот класс и удалить его

2022-10-02 20:24 UTC, alexache commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
Это можно не комментировать. Если проблема была с локальным запуском, то нужно было указать активный профиль в настройках запуска

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
> +    @Column(name = "requestor_id")
Тут тоже бы хорошо иметь User requestor с помощью аннотаций JoinColumn, ManyToOne

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
>  public interface ItemRepository {
Этот класс уже не очень нужен

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(name = "owner_id")
Тут тоже бы хорошо иметь User owner с помощью аннотаций JoinColumn, ManyToOne

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long request;
Тут тоже бы хорошо иметь ItemRequest request с помощью аннотаций JoinColumn, ManyToOne

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "item_id")
Тут тоже бы хорошо иметь Item item с помощью аннотаций JoinColumn, ManyToOne

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private Long authorId;
Тут тоже бы хорошо иметь User author с помощью аннотаций JoinColumn, ManyToOne

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +@Service
Эта аннотация не подходит для интерфейса

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "booker_id")
Тут тоже бы хорошо иметь User booker с помощью аннотаций JoinColumn, ManyToOne

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        } else if (userJpaRepository.findById(owner).isEmpty()) {
userJpaRepository.findById(owner).get() лучше вынести в переменную

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Optional<Booking> bookingOpt = bookingJpaRepository.findById(bookingId);
Можно писать проще Booking booking = bookingJpaRepository.findById(bookingId).orElseThrow(() ->  new ItemNotFoundException("Вещи не существует"));
и дальше по аналогии

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            itemOpt = itemJpaRepository.findById(bookingOpt.get().getItemId());
Здесь уже будет NullPointerException до проверки на наличие значения строкой ниже

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (bookingJpaRepository.findById(bookingId).isEmpty()) {
Два одинаковых вызова, нужна переменная

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(x -> toBookingDto(x, itemJpaRepository.findById(x.getItemId()).get(), userJpaRepository.findById(x.getBookerId()).get()))
Это лучше исправить на уровне класса Booking, иначе тут очень много сложных и повторяющихся запросов

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .sorted(Comparator.comparing(BookingDto::getStart)
Сортировать можно силами JpaRepository / SQL

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Booking> rawBookings = bookingJpaRepository.findAll()
Почему не воспользоваться запросом SQL, который сразу вернет верный список бронирований вещей владельца вместо такого количества лишних запросов?

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .sorted(Comparator.comparing(BookingDto::getStart)
Похожие комментарии, что и в методе выше

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemRepository.findById(itemId).isEmpty()) {
Лучше завести переменную, чем делать повторяющиеся запросы

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!bookings
Мне кажется тут много лишней работы с таким условием

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(x -> x.getBookerId().equals(owner) && x.getStatus().equals(BookStatus.APPROVED))
Почему это не включить в SQL запрос?

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else if (bookingJpaRepository.findByItemId(itemId)
Это уже более сложные вариации проверок. Достаточно проверять то, что выше, что бронирования было и оно завершено

2022-10-02 20:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +                && getAllUsers().stream()
Почему бы не написать запрос SQL с поиском по email? Любая фильтрация-сортировка, сделанная запросов к базе, будет лучше той, что написана в джаве

2022-10-04 18:02 UTC, Sweta304 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else if (bookingJpaRepository.findByItemId(itemId)
Не придумала как еще проверить, что комментарий не относится к вещи, бронирование которой еще не окончено. Если убрать это условие, то падает на тесте "Add comment to item 2 from user5 failed by future booking" - у пользователя может быть одобренное бронирование этой вещи, но он в прогрессе либо еще не началось

2022-10-04 21:23 UTC, Sweta304 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            itemOpt = itemJpaRepository.findById(bookingOpt.get().getItemId());
Почему? мы же уже проверили что bookingOpt.isPresent(), а itemOpt это Optional

2022-10-06 17:49 UTC, Sweta304 commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
> +    @Column(name = "requestor_id")
эта функциональность в 15 спринте, сделаю

2022-10-06 20:49 UTC, Sweta304 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Booking> rawBookings = bookingJpaRepository.findAll()
В таблице бронирований нет владельца вещи, не могу разобраться как можно написать запрос. Инфа о владельце только в таблице Items

2022-10-07 19:51 UTC, alexache approved these changes

2022-10-07 19:51 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public Booking addBooking(@RequestBody @Valid BookingIncomingDto bookingIncomingDto, @RequestHeader("X-Sharer-User-Id") Long booker) throws ItemNotAvailableException, ItemNotFoundException, Incor
Контроллер должен получать на вход DTO объекты, и возвращать тоже DTO объекты. Это в теории могут быть разные классы у объектов, но точно не класс для хранения данных в базе

2022-10-07 19:51 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    Booking addBooking(BookingIncomingDto bookingIncomingDto, Long owner) throws ItemNotAvailableException, ItemNotFoundException, IncorrectBookingException, UserNotFoundException;
Здесь тоже должны возвращаться Dto объекты

2022-10-07 19:51 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Booking> rawBookings = bookingJpaRepository.findAll()
В таблице бронирования есть ссылка на объект вещи. а у объекта вещи есть владелец, то есть это можно сделать одним запросом

2022-10-22 09:37 UTC, merged