Add item requests
Sweta304/java-shareit pull request #3
Opened 2022-10-22 17:47 UTC by Sweta304

2022-10-24 08:44 UTC, alexache requested changes

2022-10-24 08:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
ДТО объект, который хранит не-дто модели в себе, выглядит немного странно

2022-10-24 08:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                if (from != null && size != null) {
Это выглядит общей часть для всех кейсов, ее стоит вынести до свитча, чтобы не дублировать столько раз

2022-10-24 08:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/controller/ItemRequestController.java
> +    public ItemRequestDto addItemRequest(@RequestBody @Valid ItemRequest itemRequest, @RequestHeader("X-Sharer-User-Id") Long requestor) throws UserNotFoundException, RequestNotCorrectException {
Надо работать только с  дто в контроллере

2022-10-24 08:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> searchItem(@RequestParam String text, @RequestParam(required = false) Integer from, @RequestParam(required = false) Integer size) throws PaginationNotCorrectException {
На аргументы from и size лучше написать значения по умолчанию. тогда и не придется поддерживать вариант, что они могут быть null, и код в сервисе станет почище

2022-10-24 08:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +        if (itemRequest.getDescription() == null
Такие проверки лучше иметь ближе к контроллеру

2022-10-24 08:44 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
Не хватает модификаторов доступа у полей (в остальных тестовых классах тоже)

2022-10-24 08:44 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    BookingService bookingService;
Не очень понятно с этим тестом. Копипаст от теста на контроллер букинга?

2022-10-27 20:52 UTC, Sweta304 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    BookingService bookingService;
да, скопипастила, а переписать забыла :(

2022-10-30 20:26 UTC, alexache approved these changes

2022-10-30 20:26 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  import javax.persistence.*;
Кстати по коду, который ниже  - @Data/@EqualsAndHashCode нельзя использовать в классах-моделях - тех, что хранятся в БД

2022-10-30 20:26 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/ShareItIntegrationTest.java
> +@AutoConfigureTestDatabase
Для полноценного интеграционного теста не хватает реальной постгрес БД, но пусть будет так

2022-10-31 18:04 UTC, merged